<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace sys\db;

use \php\Boot;
use \haxe\ds\List_hx;

interface ResultSet {
	/**
	 * @param int $n
	 * 
	 * @return int
	 */
	public function getIntResult ($n) ;


	/**
	 * @return bool
	 */
	public function hasNext () ;


	/**
	 * @return mixed
	 */
	public function next () ;


	/**
	 * @return List_hx
	 */
	public function results () ;
}


Boot::registerClass(ResultSet::class, 'sys.db.ResultSet');
