<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

use \php\Boot;
use \php\_Boot\HxDynamicStr;
use \tink\template\_Html\HtmlBuffer_Impl_;
use \tink\template\_Html\Html_Impl_;

class Rss {
	/**
	 * @var string
	 */
	public $authoe;
	/**
	 * @var string
	 */
	public $category;
	/**
	 * @var string
	 */
	public $description;
	/**
	 * @var string
	 */
	public $explicit;
	/**
	 * @var \Array_hx
	 */
	public $items;
	/**
	 * @var string
	 */
	public $langage;
	/**
	 * @var string
	 */
	public $logo;
	/**
	 * @var string
	 */
	public $owner;
	/**
	 * @var string
	 */
	public $subtitles;
	/**
	 * @var string
	 */
	public $summary;
	/**
	 * @var string
	 */
	public $title;
	/**
	 * @var string
	 */
	public $url;


	/**
	 * @return void
	 */
	public function __construct () {
		#src/Rss.hx:56: characters 5-24
		$this->items = new \Array_hx();
	}


	/**
	 * @return string
	 */
	public function rssTemplate () {
		#src///rssTemplate.tt:1: character 1
		$ret = Html_Impl_::buffer();
		#src///rssTemplate.tt:1: character 1
		$ret->arr[$ret->length] = "<?xml version=\"1.0\"  encoding=\"UTF-8\"?>\x0A\x0A<rss xmlns:itunes=\"http://www.itunes.com/dtds/podcast-1.0.dtd\"   version=\"2.0\">\x0A<channel>\x0A\x0A<title>";
		#src///rssTemplate.tt:1: character 1
		++$ret->length;

		#src///rssTemplate.tt:1: characters 142-147
		$b = Html_Impl_::escape($this->title);
		#src///rssTemplate.tt:1: characters 142-147
		$ret->arr[$ret->length] = $b;
		#src///rssTemplate.tt:1: characters 142-147
		++$ret->length;

		#src///rssTemplate.tt:1: characters 142-149
		$ret->arr[$ret->length] = "</title>\x0A<language>fr-fr</language>\x0A<itunes:subtitle>Subtitle of podcast</itunes:subtitle>\x0A<itunes:author>zelote</itunes:author>\x0A<link>http://www.zecastpod.postite.com</link>\x0A<itunes:summary>Description of podcast.</itunes:summary>\x0A<description>Description of podcast.</description>\x0A<itunes:owner>\x0A    <itunes:name>zélote</itunes:name>\x0A    <itunes:email>zelote@postite.com</itunes:email>\x0A</itunes:owner>\x0A<itunes:explicit>no</itunes:explicit>\x0A<itunes:image href=\"";
		#src///rssTemplate.tt:1: characters 142-149
		++$ret->length;

		#src///rssTemplate.tt:1: characters 615-619
		$b1 = Html_Impl_::escape($this->logo);
		#src///rssTemplate.tt:1: characters 615-619
		$ret->arr[$ret->length] = $b1;
		#src///rssTemplate.tt:1: characters 615-619
		++$ret->length;

		#src///rssTemplate.tt:1: characters 615-622
		$ret->arr[$ret->length] = "\" />\x0A<itunes:category text=\"Kids &amp; Family\"/> \x0A\x0A    ";
		#src///rssTemplate.tt:1: characters 615-622
		++$ret->length;

		#src///rssTemplate.tt:1: characters 684-697
		$_g = 0;
		#src///rssTemplate.tt:1: characters 684-697
		$_g1 = $this->items;
		#src///rssTemplate.tt:1: characters 684-697
		while ($_g < $_g1->length) {
			#src///rssTemplate.tt:1: characters 684-688
			$item = ($_g1->arr[$_g] ?? null);
			#src///rssTemplate.tt:1: characters 684-697
			$_g = $_g + 1;
			#src///rssTemplate.tt:1: characters 684-700
			$ret->arr[$ret->length] = " \x0A    <item>\x0A      <title>";
			#src///rssTemplate.tt:1: characters 684-700
			++$ret->length;

			#src///rssTemplate.tt:1: characters 729-739
			$b2 = Html_Impl_::escape($item->title);
			#src///rssTemplate.tt:1: characters 729-739
			$ret->arr[$ret->length] = $b2;
			#src///rssTemplate.tt:1: characters 729-739
			++$ret->length;

			#src///rssTemplate.tt:1: characters 729-742
			$ret->arr[$ret->length] = "</title>\x0A      <itunes:summary>";
			#src///rssTemplate.tt:1: characters 729-742
			++$ret->length;

			#src///rssTemplate.tt:1: characters 775-791
			$b3 = Html_Impl_::escape($item->description);
			#src///rssTemplate.tt:1: characters 775-791
			$ret->arr[$ret->length] = $b3;
			#src///rssTemplate.tt:1: characters 775-791
			++$ret->length;

			#src///rssTemplate.tt:1: characters 775-794
			$ret->arr[$ret->length] = "</itunes:summary>\x0A        <description><![CDATA[<img src=\"";
			#src///rssTemplate.tt:1: characters 775-794
			++$ret->length;

			#src///rssTemplate.tt:1: characters 854-864
			$b4 = Html_Impl_::escape($item->image);
			#src///rssTemplate.tt:1: characters 854-864
			$ret->arr[$ret->length] = $b4;
			#src///rssTemplate.tt:1: characters 854-864
			++$ret->length;

			#src///rssTemplate.tt:1: characters 854-866
			$ret->arr[$ret->length] = "\"/>";
			#src///rssTemplate.tt:1: characters 854-866
			++$ret->length;

			#src///rssTemplate.tt:1: characters 871-887
			$b5 = Html_Impl_::escape($item->description);
			#src///rssTemplate.tt:1: characters 871-887
			$ret->arr[$ret->length] = $b5;
			#src///rssTemplate.tt:1: characters 871-887
			++$ret->length;

			#src///rssTemplate.tt:1: characters 871-889
			$ret->arr[$ret->length] = "]]></description>\x0A      \x0A      <enclosure url=\"";
			#src///rssTemplate.tt:1: characters 871-889
			++$ret->length;

			#src///rssTemplate.tt:1: characters 938-952
			$b6 = Html_Impl_::escape($item->sound->url);
			#src///rssTemplate.tt:1: characters 938-952
			$ret->arr[$ret->length] = $b6;
			#src///rssTemplate.tt:1: characters 938-952
			++$ret->length;

			#src///rssTemplate.tt:1: characters 938-954
			$ret->arr[$ret->length] = "\" type=\"";
			#src///rssTemplate.tt:1: characters 938-954
			++$ret->length;

			#src///rssTemplate.tt:1: characters 964-979
			$b7 = Html_Impl_::escape($item->sound->type);
			#src///rssTemplate.tt:1: characters 964-979
			$ret->arr[$ret->length] = $b7;
			#src///rssTemplate.tt:1: characters 964-979
			++$ret->length;

			#src///rssTemplate.tt:1: characters 964-981
			$ret->arr[$ret->length] = "\" length=\"";
			#src///rssTemplate.tt:1: characters 964-981
			++$ret->length;

			#src///rssTemplate.tt:1: characters 993-1010
			$b8 = Html_Impl_::of(HxDynamicStr::wrap($item->sound)->length);
			#src///rssTemplate.tt:1: characters 993-1010
			$ret->arr[$ret->length] = $b8;
			#src///rssTemplate.tt:1: characters 993-1010
			++$ret->length;

			#src///rssTemplate.tt:1: characters 993-1012
			$ret->arr[$ret->length] = "\"></enclosure>\x0A      <pubDate>";
			#src///rssTemplate.tt:1: characters 993-1012
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1045-1054
			$b9 = Html_Impl_::escape($item->date);
			#src///rssTemplate.tt:1: characters 1045-1054
			$ret->arr[$ret->length] = $b9;
			#src///rssTemplate.tt:1: characters 1045-1054
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1045-1057
			$ret->arr[$ret->length] = "</pubDate>\x0A\x0A        <author>\x0A        ";
			#src///rssTemplate.tt:1: characters 1045-1057
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1097-1108
			$b10 = Html_Impl_::escape($item->author);
			#src///rssTemplate.tt:1: characters 1097-1108
			$ret->arr[$ret->length] = $b10;
			#src///rssTemplate.tt:1: characters 1097-1108
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1097-1111
			$ret->arr[$ret->length] = "\x0A        </author>\x0A        <itunes:duration>";
			#src///rssTemplate.tt:1: characters 1097-1111
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1157-1170
			$b11 = Html_Impl_::escape($item->duration);
			#src///rssTemplate.tt:1: characters 1157-1170
			$ret->arr[$ret->length] = $b11;
			#src///rssTemplate.tt:1: characters 1157-1170
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1157-1173
			$ret->arr[$ret->length] = "</itunes:duration>\x0A        <itunes:explicit>";
			#src///rssTemplate.tt:1: characters 1157-1173
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1219-1232
			$b12 = Html_Impl_::escape($item->explicit);
			#src///rssTemplate.tt:1: characters 1219-1232
			$ret->arr[$ret->length] = $b12;
			#src///rssTemplate.tt:1: characters 1219-1232
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1219-1234
			$ret->arr[$ret->length] = "</itunes:explicit>\x0A      <guid>";
			#src///rssTemplate.tt:1: characters 1219-1234
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1268-1282
			$b13 = Html_Impl_::escape($item->permalink);
			#src///rssTemplate.tt:1: characters 1268-1282
			$ret->arr[$ret->length] = $b13;
			#src///rssTemplate.tt:1: characters 1268-1282
			++$ret->length;

			#src///rssTemplate.tt:1: characters 1268-1285
			$ret->arr[$ret->length] = "</guid>\x0A      \x0A    </item>\x0A    ";
			#src///rssTemplate.tt:1: characters 1268-1285
			++$ret->length;


		}

		#src///rssTemplate.tt:1: characters 1319-1325
		$ret->arr[$ret->length] = "\x0A</channel>\x0A</rss>";
		#src///rssTemplate.tt:1: characters 1319-1325
		++$ret->length;


		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/947e330e7f57a4877b12c253baac6311cfb5530b/src/tink/template/Generator.hx:121: characters 19-30
		return HtmlBuffer_Impl_::collapse($ret);
	}
}


Boot::registerClass(Rss::class, 'Rss');
