<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

use \php\Boot;
use \php\_Boot\HxAnon;

class RssApi {
	/**
	 * @var \Array_hx
	 */
	static public $days;
	/**
	 * @var \Array_hx
	 */
	static public $months;


	/**
	 * @return void
	 */
	public function __construct () {
	}


	/**
	 * @return \Rss
	 */
	public function getRss () {
		#src/RssApi.hx:11: characters 12-35
		\DBApi::get_instance()->getAll();
		#src/RssApi.hx:12: characters 3-23
		$rss = new \Rss();
		#src/RssApi.hx:13: characters 3-17
		$rss->items = new \Array_hx();
		#src/RssApi.hx:14: characters 3-19
		$counter = 1;
		#src/RssApi.hx:15: lines 15-36
		\DBApi::get_instance()->getAll()->map(function ($it)  use (&$counter, &$rss) {
			#src/RssApi.hx:16: characters 4-38
			$item = new HxAnon();
			#src/RssApi.hx:17: characters 13-26
			$item->id = $it->id;
			#src/RssApi.hx:18: characters 4-25
			$item->title = $it->title;
			#src/RssApi.hx:19: characters 4-30
			$item->description = $it->desc;
			#src/RssApi.hx:20: characters 4-42
			$item->permalink = "" . (\Consts::get_baseUrl()??'null') . "/pod/" . ($it->id??'null');
			#src/RssApi.hx:21: characters 4-49
			$item->author = "zelote@postite.com (zel kert)";
			#src/RssApi.hx:22: characters 4-30
			$item->duration = "00:32:16";
			#src/RssApi.hx:23: characters 13-49
			$item->image = "" . (\Consts::get_baseUrl()??'null') . "/" . ($it->imageUrl??'null');
			#src/RssApi.hx:24: characters 4-24
			$item->explicit = "no";
			#src/RssApi.hx:26: characters 11-33
			$tmp = "" . (\Consts::get_baseUrl()??'null') . "/" . ($it->soundUrl??'null');
			#src/RssApi.hx:25: lines 25-29
			$item->sound = new HxAnon([
				"url" => $tmp,
				"length" => $it->length,
				"type" => "audio/mpeg",
			]);
			#src/RssApi.hx:31: characters 4-26
			$date = \Date::now();
			#src/RssApi.hx:32: characters 4-53
			$date = \Date::fromTime($date->getTime() + -10000000 * $counter);
			#src/RssApi.hx:33: characters 4-113
			$item->date = \DateTools::format($date, "" . ((RssApi::$days->arr[$date->getDay()] ?? null)??'null') . ", %d " . ((RssApi::$months->arr[$date->getMonth()] ?? null)??'null') . " %Y %H:%M:%S +0100");
			#src/RssApi.hx:34: characters 4-25
			$counter = $counter + 1;
			#src/RssApi.hx:35: characters 4-24
			$_this = $rss->items;
			#src/RssApi.hx:35: characters 4-24
			$_this->arr[$_this->length] = $item;
			#src/RssApi.hx:35: characters 4-24
			++$_this->length;

		});
		#src/RssApi.hx:37: characters 9-37
		$rss->logo = "\$baseUrl/logo.png";
		#src/RssApi.hx:38: characters 3-26
		$rss->title = "zecastpod";
		#src/RssApi.hx:39: characters 3-13
		return $rss;
	}


	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


self::$days = \Array_hx::wrap([
	"Sun",
	"Mon",
	"Tue",
	"Wed",
	"Thu",
	"Fri",
	"Sat",
]);
self::$months = \Array_hx::wrap([
	"Jan",
	"Feb",
	"Mar",
	"Apr",
	"May",
	"Jun",
	"Jul",
	"Aug",
	"Sep",
	"Oct",
	"Nov",
	"Dec",
]);
	}
}


Boot::registerClass(RssApi::class, 'RssApi');
RssApi::__hx__init();
