<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

use \php\Boot;
use \php\_Boot\HxString;

/**
 * This class gives you access to many base functionalities of system platforms. Looks in `sys` sub packages for more system APIs.
 */
class Sys {
	/**
	 * @var string
	 */
	static public $_programPath;


	/**
	 * Get the current working directory (usually the one in which the program was started)
	 * 
	 * @return string
	 */
	static public function getCwd () {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:67: characters 3-29
		$cwd = getcwd();
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:68: characters 3-32
		if ($cwd === false) {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:68: characters 21-32
			return null;
		}
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:69: characters 3-35
		$l = HxString::substr($cwd, -1);
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:70: characters 3-59
		return ($cwd??'null') . (((($l === "/") || ($l === "\\") ? "" : "/"))??'null');
	}


	/**
	 * Print any value on the standard output, followed by a newline.
	 * 
	 * @param mixed $v
	 * 
	 * @return void
	 */
	static public function println ($v) {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:36: characters 3-11
		echo(\Std::string($v));
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:37: characters 3-14
		echo("\x0A");
	}


	/**
	 * Returns the absolute path to the current program file that we are running.
	 * Concretely, for an executable binary, it returns the path to the binary.
	 * For a script (e.g. a PHP file), it returns the path to the script.
	 * 
	 * @return string
	 */
	static public function programPath () {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/_std/Sys.hx:119: characters 3-22
		return Sys::$_programPath;
	}


	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


self::$_programPath = (realpath($_SERVER["SCRIPT_FILENAME"]) ?: null);
	}
}


Boot::registerClass(Sys::class, 'Sys');
Sys::__hx__init();
