<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\http\_Response;

use \tink\http\ResponseHeaderBase;
use \php\Boot;
use \tink\http\Message;
use \tink\streams\StreamObject;

class OutgoingResponseData extends Message {
	/**
	 * @param ResponseHeaderBase $header
	 * @param StreamObject $body
	 * 
	 * @return void
	 */
	public function __construct ($header, $body) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:61: characters 9-83
		parent::__construct($header, $body);
	}
}


Boot::registerClass(OutgoingResponseData::class, 'tink.http._Response.OutgoingResponseData');
