<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\http\_Response;

use \tink\http\ResponseHeaderBase;
use \php\Boot;
use \tink\io\StreamParserObject;

final class ResponseHeader_Impl_ {
	/**
	 * @param int $statusCode
	 * @param string $reason
	 * @param \Array_hx $fields
	 * @param string $protocol
	 * 
	 * @return ResponseHeaderBase
	 */
	static public function _new ($statusCode, $reason = null, $fields = null, $protocol = "HTTP/1.1") {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:16: character 17
		if ($protocol === null) {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:16: character 17
			$protocol = "HTTP/1.1";
		}
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:16: character 17
		return new ResponseHeaderBase($statusCode, $reason, $fields, $protocol);
	}


	/**
	 * @param \Array_hx $fields
	 * 
	 * @return ResponseHeaderBase
	 */
	static public function fromHeaderFields ($fields) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:25: characters 12-42
		return new ResponseHeaderBase(200, null, $fields, "HTTP/1.1");
	}


	/**
	 * @param int $code
	 * 
	 * @return ResponseHeaderBase
	 */
	static public function fromStatusCode ($code) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:21: characters 12-36
		return new ResponseHeaderBase($code, null, null, "HTTP/1.1");
	}


	/**
	 * @return StreamParserObject
	 */
	static public function parser () {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Response.hx:28: characters 5-39
		return ResponseHeaderBase::parser();
	}
}


Boot::registerClass(ResponseHeader_Impl_::class, 'tink.http._Response.ResponseHeader_Impl_');
