<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace views\__impl;

use \php\Boot;
use \tink\template\_Html\HtmlBuffer_Impl_;
use \tink\template\_Html\Html_Impl_;

class Coolrss {
	/**
	 * @param \Rss $rss
	 * 
	 * @return string
	 */
	static public function render ($rss) {
		#src//views/Coolrss.tt:1: characters 25-36
		$ret = Html_Impl_::buffer();
		#src//views/Coolrss.tt:1: characters 25-36
		$ret->arr[$ret->length] = "\x0A";
		#src//views/Coolrss.tt:1: characters 25-36
		++$ret->length;

		#src//views/Coolrss.tt:1: characters 44-61
		$_g = 0;
		#src//views/Coolrss.tt:1: characters 44-61
		$_g1 = $rss->items;
		#src//views/Coolrss.tt:1: characters 44-61
		while ($_g < $_g1->length) {
			#src//views/Coolrss.tt:1: characters 44-48
			$item = ($_g1->arr[$_g] ?? null);
			#src//views/Coolrss.tt:1: characters 44-61
			$_g = $_g + 1;
			#src//views/Coolrss.tt:1: characters 44-64
			$ret->arr[$ret->length] = "\x0A    <div class=\"item\">\x0A        <a href=\"/pod/";
			#src//views/Coolrss.tt:1: characters 44-64
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 112-119
			$b = Html_Impl_::of($item->id);
			#src//views/Coolrss.tt:1: characters 112-119
			$ret->arr[$ret->length] = $b;
			#src//views/Coolrss.tt:1: characters 112-119
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 112-121
			$ret->arr[$ret->length] = "\"><h4>";
			#src//views/Coolrss.tt:1: characters 112-121
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 130-140
			$b1 = Html_Impl_::escape($item->title);
			#src//views/Coolrss.tt:1: characters 130-140
			$ret->arr[$ret->length] = $b1;
			#src//views/Coolrss.tt:1: characters 130-140
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 130-143
			$ret->arr[$ret->length] = "</h4></a>\x0A        <img class=\"item-image\" src=\"";
			#src//views/Coolrss.tt:1: characters 130-143
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 192-202
			$b2 = Html_Impl_::escape($item->image);
			#src//views/Coolrss.tt:1: characters 192-202
			$ret->arr[$ret->length] = $b2;
			#src//views/Coolrss.tt:1: characters 192-202
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 192-204
			$ret->arr[$ret->length] = "\" />\x0A        <p>";
			#src//views/Coolrss.tt:1: characters 192-204
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 222-238
			$b3 = Html_Impl_::escape($item->description);
			#src//views/Coolrss.tt:1: characters 222-238
			$ret->arr[$ret->length] = $b3;
			#src//views/Coolrss.tt:1: characters 222-238
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 222-240
			$ret->arr[$ret->length] = "</p>\x0A        <div class=\"modif\"><a href=\"/modif/";
			#src//views/Coolrss.tt:1: characters 222-240
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 290-297
			$b4 = Html_Impl_::of($item->id);
			#src//views/Coolrss.tt:1: characters 290-297
			$ret->arr[$ret->length] = $b4;
			#src//views/Coolrss.tt:1: characters 290-297
			++$ret->length;

			#src//views/Coolrss.tt:1: characters 290-299
			$ret->arr[$ret->length] = "\">x</a></div>\x0A    </div>\x0A";
			#src//views/Coolrss.tt:1: characters 290-299
			++$ret->length;


		}

		#src//views/Coolrss.tt:1: characters 327-333
		$ret->arr[$ret->length] = "\x0A";
		#src//views/Coolrss.tt:1: characters 327-333
		++$ret->length;


		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/947e330e7f57a4877b12c253baac6311cfb5530b/src/tink/template/Generator.hx:121: characters 19-30
		return HtmlBuffer_Impl_::collapse($ret);
	}
}


Boot::registerClass(Coolrss::class, 'views.__impl.Coolrss');
