<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\url\_Auth;

use \php\Boot;

final class Auth_Impl_ {


	/**
	 * @param string $user
	 * @param string $password
	 * 
	 * @return string
	 */
	static public function _new ($user, $password) {
		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:11: character 17
		return "" . ($user??'null') . ":" . ($password??'null');
	}


	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	static public function get_password ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:21: lines 21-22
		if ($this1 === null) {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:21: characters 25-29
			return null;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:22: characters 12-30
			return (\Array_hx::wrap(explode(":", $this1))->arr[1] ?? null);
		}
	}


	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	static public function get_user ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:16: lines 16-17
		if ($this1 === null) {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:16: characters 25-29
			return null;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:17: characters 12-30
			return (\Array_hx::wrap(explode(":", $this1))->arr[0] ?? null);
		}
	}


	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	static public function toString ($this1) {
		#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:25: characters 12-46
		if ($this1 === null) {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:25: characters 30-32
			return "";
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_url/0.4.1/haxelib/src/tink/url/Auth.hx:25: characters 39-45
			return "" . ($this1??'null') . "@";
		}
	}
}


Boot::registerClass(Auth_Impl_::class, 'tink.url._Auth.Auth_Impl_');
Boot::registerGetters('tink\\url\\_Auth\\Auth_Impl_', [
	'password' => true,
	'user' => true
]);
