<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace asys\io;

use \sys\io\File as IoFile;
use \tink\core\Outcome;
use \php\Boot;
use \php\_Boot\HxException;
use \tink\io\SinkObject;
use \tink\io\_Worker\Worker_Impl_;
use \tink\core\TypedError;
use \tink\core\_Future\FutureObject;
use \tink\core\_Future\SyncFuture;
use \tink\io\std\InputSource;
use \haxe\io\Bytes;
use \tink\streams\StreamObject;
use \tink\core\Noise;
use \tink\io\_Sink\SinkYielding_Impl_;
use \tink\core\_Lazy\LazyConst;
use \php\_Boot\HxAnon;

class File {
	/**
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FutureObject
	 */
	static public function append ($path, $binary = true) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:255: lines 255-258
		if ($binary === null) {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:255: lines 255-258
			$binary = true;
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:255: lines 255-258
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:256: lines 256-257
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:255: lines 255-258
			$v = Outcome::Success(IoFile::append($path, $binary));
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:257: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:255: lines 255-258
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 257,
				"className" => "asys.io.File",
				"methodName" => "append",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:255: lines 255-258
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $srcPath
	 * @param string $dstPath
	 * 
	 * @return FutureObject
	 */
	static public function copy ($srcPath, $dstPath) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:261: lines 261-267
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:262: lines 262-266
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:263: characters 5-39
			IoFile::copy($srcPath, $dstPath);
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:261: lines 261-267
			$v = Outcome::Success(Noise::Noise());
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:266: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:261: lines 261-267
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 266,
				"className" => "asys.io.File",
				"methodName" => "copy",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:261: lines 261-267
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * 
	 * @return FutureObject
	 */
	static public function getBytes ($path) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:228: lines 228-231
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:229: lines 229-230
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:228: lines 228-231
			$v = Outcome::Success(IoFile::getBytes($path));
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:230: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:228: lines 228-231
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 230,
				"className" => "asys.io.File",
				"methodName" => "getBytes",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:228: lines 228-231
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * 
	 * @return FutureObject
	 */
	static public function getContent ($path) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:213: lines 213-216
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:214: lines 214-215
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:213: lines 213-216
			$v = Outcome::Success(IoFile::getContent($path));
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:215: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:213: lines 213-216
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 215,
				"className" => "asys.io.File",
				"methodName" => "getContent",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:213: lines 213-216
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FutureObject
	 */
	static public function read ($path, $binary = true) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:243: lines 243-246
		if ($binary === null) {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:243: lines 243-246
			$binary = true;
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:243: lines 243-246
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:244: lines 244-245
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:243: lines 243-246
			$v = Outcome::Success(IoFile::read($path, $binary));
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:245: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:243: lines 243-246
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 245,
				"className" => "asys.io.File",
				"methodName" => "read",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:243: lines 243-246
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return StreamObject
	 */
	static public function readStream ($path, $binary = true) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 3-68
		if ($binary === null) {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 3-68
			$binary = true;
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 10-68
		$input = IoFile::read($path);
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 10-68
		$options = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 10-68
		$options = new HxAnon();
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 10-68
		$tmp = Worker_Impl_::ensure($options->worker);
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 10-68
		$_g = $options->chunkSize;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:21: characters 10-68
		return new InputSource("asys read stream", $input, $tmp, Bytes::alloc(($_g === null ? 65536 : $_g)), 0);
	}


	/**
	 * @param string $path
	 * @param Bytes $bytes
	 * 
	 * @return FutureObject
	 */
	static public function saveBytes ($path, $bytes) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:234: lines 234-240
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:235: lines 235-239
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:236: characters 5-39
			IoFile::saveBytes($path, $bytes);
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:234: lines 234-240
			$v = Outcome::Success(Noise::Noise());
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:239: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:234: lines 234-240
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 239,
				"className" => "asys.io.File",
				"methodName" => "saveBytes",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:234: lines 234-240
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * @param string $content
	 * 
	 * @return FutureObject
	 */
	static public function saveContent ($path, $content) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:219: lines 219-225
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:220: lines 220-224
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:221: characters 5-43
			IoFile::saveContent($path, $content);
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:219: lines 219-225
			$v = Outcome::Success(Noise::Noise());
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:224: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:219: lines 219-225
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 224,
				"className" => "asys.io.File",
				"methodName" => "saveContent",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:219: lines 219-225
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FutureObject
	 */
	static public function write ($path, $binary = true) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:249: lines 249-252
		if ($binary === null) {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:249: lines 249-252
			$binary = true;
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:249: lines 249-252
		$v = null;
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:250: lines 250-251
		try {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:249: lines 249-252
			$v = Outcome::Success(IoFile::write($path, $binary));
		} catch (\Throwable $__hx__caught_e) {
			$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
			$e = $__hx__real_e;
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:251: characters 41-43
			$v1 = "" . (\Std::string($e)??'null');
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:249: lines 249-252
			$v = Outcome::Failure(new TypedError(null, $v1, new HxAnon([
				"fileName" => "asys/io/File.hx",
				"lineNumber" => 251,
				"className" => "asys.io.File",
				"methodName" => "write",
			])));
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:249: lines 249-252
		return new SyncFuture(new LazyConst($v));
	}


	/**
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return SinkObject
	 */
	static public function writeStream ($path, $binary = true) {
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:29: characters 3-69
		if ($binary === null) {
			#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:29: characters 3-69
			$binary = true;
		}
		#/Users/ut/Documents/LAB/localLibs/asys/asys/io/File.hx:29: characters 3-69
		return SinkYielding_Impl_::ofOutput("asys write stream", IoFile::write($path));
	}
}


Boot::registerClass(File::class, 'asys.io.File');
