<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\io;

use \php\Boot;

class SimpleBytewiseParser extends BytewiseParser {
	/**
	 * @var \Closure
	 */
	public $_read;


	/**
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	public function __construct ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:152: characters 5-19
		$this->_read = $f;
	}


	/**
	 * @param int $char
	 * 
	 * @return ParseStep
	 */
	public function read ($char) {
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:155: characters 5-23
		return ($this->_read)($char);
	}
}


Boot::registerClass(SimpleBytewiseParser::class, 'tink.io.SimpleBytewiseParser');
