<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\io;

use \tink\chunk\ChunkObject;
use \php\Boot;
use \haxe\io\Bytes;
use \tink\_Chunk\Chunk_Impl_;
use \haxe\io\_BytesData\Container;
use \haxe\ds\Option;

class Splitter extends BytewiseParser {
	/**
	 * @var ChunkObject
	 */
	public $buf;
	/**
	 * @var ChunkObject
	 */
	public $delim;


	/**
	 * @param ChunkObject $delim
	 * 
	 * @return void
	 */
	public function __construct ($delim) {
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:112: characters 13-24
		$this->buf = Chunk_Impl_::$EMPTY;
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:114: characters 5-23
		$this->delim = $delim;
	}


	/**
	 * @param int $char
	 * 
	 * @return ParseStep
	 */
	public function read ($char) {
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:118: characters 5-37
		if ($char === -1) {
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:118: characters 20-37
			return ParseStep::Done(Option::None());
		}
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:120: characters 11-14
		$tmp = $this->buf;
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:120: characters 11-42
		$s = chr($char);
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:120: characters 5-42
		$this->buf = Chunk_Impl_::catChunk($tmp, Chunk_Impl_::ofBytes(new Bytes(strlen($s), new Container($s))));
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:121: lines 121-143
		if ($this->buf->getLength() >= $this->delim->getLength()) {
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:122: characters 7-34
			$bcursor = $this->buf->getCursor();
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:123: characters 7-48
			$delta = $this->buf->getLength() - $this->delim->getLength();
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:123: characters 7-48
			$bcursor->moveTo($bcursor->currentPos + $delta);

			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:124: characters 7-36
			$dcursor = $this->delim->getCursor();
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:126: lines 126-134
			$_g1 = 0;
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:126: lines 126-134
			$_g = $this->delim->getLength();
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:126: lines 126-134
			while ($_g1 < $_g) {
				#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:126: lines 126-134
				$_g1 = $_g1 + 1;
				#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:127: lines 127-133
				if ($bcursor->currentByte !== $dcursor->currentByte) {
					#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:128: characters 11-28
					return ParseStep::Progressed();
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:131: characters 11-25
					$bcursor->next();
					#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:132: characters 11-25
					$dcursor->next();
				}
			}

			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:135: characters 7-77
			$out = ParseStep::Done(Option::Some($this->buf->slice(0, $bcursor->currentPos - $this->delim->getLength())));
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:136: characters 7-24
			$this->buf = Chunk_Impl_::$EMPTY;
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:137: characters 7-17
			return $out;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/StreamParser.hx:141: characters 7-17
			return ParseStep::Progressed();
		}
	}
}


Boot::registerClass(Splitter::class, 'tink.io.Splitter');
