<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\io;

use \tink\core\Outcome;
use \php\Boot;
use \tink\chunk\ChunkCursor;

interface StreamParserObject {
	/**
	 * @param ChunkCursor $rest
	 * 
	 * @return Outcome
	 */
	public function eof ($rest) ;


	/**
	 * @param ChunkCursor $cursor
	 * 
	 * @return ParseStep
	 */
	public function progress ($cursor) ;
}


Boot::registerClass(StreamParserObject::class, 'tink.io.StreamParserObject');
