<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\io\_Sink;

use \php\Boot;
use \tink\core\_Future\FutureObject;
use \tink\streams\StreamObject;
use \tink\io\SinkBase;

class FutureSink extends SinkBase {
	/**
	 * @var FutureObject
	 */
	public $f;


	/**
	 * @param FutureObject $f
	 * 
	 * @return void
	 */
	public function __construct ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/Sink.hx:76: characters 5-15
		$this->f = $f;
	}


	/**
	 * @param StreamObject $source
	 * @param object $options
	 * 
	 * @return FutureObject
	 */
	public function consume ($source, $options) {
		#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/Sink.hx:79: characters 12-75
		return $this->f->flatMap(function ($sink)  use (&$source, &$options) {
			#/Users/ut/haxe/haxe_libraries/tink_io/0.6.2/haxelib/src/tink/io/Sink.hx:79: characters 38-74
			return $sink->consume($source, $options);
		})->gather();
	}
}


Boot::registerClass(FutureSink::class, 'tink.io._Sink.FutureSink');
