<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\core;

use \php\Boot;

class NamedWith {
	/**
	 * @var mixed
	 */
	public $name;
	/**
	 * @var mixed
	 */
	public $value;


	/**
	 * @param mixed $name
	 * @param mixed $value
	 * 
	 * @return void
	 */
	public function __construct ($name, $value) {
		#/Users/ut/haxe/haxe_libraries/tink_core/1.18.0/haxelib/src/tink/core/Named.hx:12: characters 5-21
		$this->name = $name;
		#/Users/ut/haxe/haxe_libraries/tink_core/1.18.0/haxelib/src/tink/core/Named.hx:13: characters 5-23
		$this->value = $value;
	}
}


Boot::registerClass(NamedWith::class, 'tink.core.NamedWith');
