<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace views;

use \php\Boot;
use \tink\template\_Html\HtmlBuffer_Impl_;
use \tink\template\_Html\Html_Impl_;

class PodPage {
	/**
	 * @var \Rec
	 */
	public $rec;


	/**
	 * @param \Rec $rec
	 * 
	 * @return void
	 */
	public function __construct ($rec) {
		#src/views/PodPage.hx:7: characters 9-21
		$this->rec = $rec;
	}


	/**
	 * @return string
	 */
	public function render () {
		#src//views/podPage.tt:1: character 1
		$ret = Html_Impl_::buffer();
		#src//views/podPage.tt:1: character 1
		$ret->arr[$ret->length] = "<div>\x0A    <h4>";
		#src//views/podPage.tt:1: character 1
		++$ret->length;

		#src//views/podPage.tt:1: characters 32-41
		$b = Html_Impl_::escape($this->rec->title);
		#src//views/podPage.tt:1: characters 32-41
		$ret->arr[$ret->length] = $b;
		#src//views/podPage.tt:1: characters 32-41
		++$ret->length;

		#src//views/podPage.tt:1: characters 17-28
		$ret->arr[$ret->length] = "</h4>\x0A    <img class=\"item-image\" src=\"/";
		#src//views/podPage.tt:1: characters 17-28
		++$ret->length;

		#src//views/podPage.tt:1: characters 70-82
		$b1 = Html_Impl_::escape($this->rec->imageUrl);
		#src//views/podPage.tt:1: characters 70-82
		$ret->arr[$ret->length] = $b1;
		#src//views/podPage.tt:1: characters 70-82
		++$ret->length;

		#src//views/podPage.tt:1: characters 70-84
		$ret->arr[$ret->length] = "\"/>\x0A    <audio controls>\x0A        <source src=\"/";
		#src//views/podPage.tt:1: characters 70-84
		++$ret->length;

		#src//views/podPage.tt:1: characters 133-145
		$b2 = Html_Impl_::escape($this->rec->soundUrl);
		#src//views/podPage.tt:1: characters 133-145
		$ret->arr[$ret->length] = $b2;
		#src//views/podPage.tt:1: characters 133-145
		++$ret->length;

		#src//views/podPage.tt:1: characters 133-147
		$ret->arr[$ret->length] = "\" type=\"audio/mpeg\">\x0A      Your browser does not support the audio element.\x0A      </audio> \x0A    <p>";
		#src//views/podPage.tt:1: characters 133-147
		++$ret->length;

		#src//views/podPage.tt:1: characters 248-256
		$b3 = Html_Impl_::escape($this->rec->desc);
		#src//views/podPage.tt:1: characters 248-256
		$ret->arr[$ret->length] = $b3;
		#src//views/podPage.tt:1: characters 248-256
		++$ret->length;

		#src//views/podPage.tt:1: characters 248-258
		$ret->arr[$ret->length] = "</p>\x0A</div>";
		#src//views/podPage.tt:1: characters 248-258
		++$ret->length;


		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/947e330e7f57a4877b12c253baac6311cfb5530b/src/tink/template/Generator.hx:121: characters 19-30
		return HtmlBuffer_Impl_::collapse($ret);
	}
}


Boot::registerClass(PodPage::class, 'views.PodPage');
