<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace views;

use \php\Boot;
use \tink\template\_Html\HtmlBuffer_Impl_;
use \tink\template\_Html\Html_Impl_;

class UpView {
	/**
	 * @var bool
	 */
	public $mod;
	/**
	 * @var string
	 */
	public $note;
	/**
	 * @var \Rec
	 */
	public $rec;
	/**
	 * @var Status
	 */
	public $status;


	/**
	 * @param string $_status
	 * @param \Rec $rec
	 * 
	 * @return void
	 */
	public function __construct ($_status = null, $rec = null) {
		#src/views/UpView.hx:19: characters 16-21
		$this->mod = false;
		#src/views/UpView.hx:18: characters 15-19
		$this->rec = null;
		#src/views/UpView.hx:17: characters 20-27
		$this->note = "boooo";
		#src/views/UpView.hx:21: lines 21-24
		if ($rec !== null) {
			#src/views/UpView.hx:22: characters 7-19
			$this->rec = $rec;
			#src/views/UpView.hx:23: characters 7-15
			$this->mod = true;
		}
		#src/views/UpView.hx:25: characters 5-34
		if ($_status === null) {
			#src/views/UpView.hx:25: characters 22-34
			$_status = "Nib";
		}
		#src/views/UpView.hx:26: lines 26-30
		$tmp = null;
		#src/views/UpView.hx:26: lines 26-30
		switch ($_status) {
			case "Cool":
				#src/views/UpView.hx:26: lines 26-30
				$tmp = "cool";
				break;
			case "Nib":
				#src/views/UpView.hx:26: lines 26-30
				$tmp = "nib";
				break;
			case "PasCool":
				#src/views/UpView.hx:26: lines 26-30
				$tmp = "pas cool";
				break;
		}
		#src/views/UpView.hx:26: lines 26-30
		$this->note = $tmp;
	}


	/**
	 * @return string
	 */
	public function form () {
		#src//views/updateform.tt:1: character 1
		$ret = Html_Impl_::buffer();
		#src//views/updateform.tt:1: character 1
		$ret->arr[$ret->length] = "\x0A<h2>";
		#src//views/updateform.tt:1: character 1
		++$ret->length;

		#src//views/updateform.tt:1: characters 32-36
		$b = Html_Impl_::escape($this->note);
		#src//views/updateform.tt:1: characters 32-36
		$ret->arr[$ret->length] = $b;
		#src//views/updateform.tt:1: characters 32-36
		++$ret->length;

		#src//views/updateform.tt:1: characters 9-16
		$ret->arr[$ret->length] = "</h2>\x0A    <form class=\"ui form segment\" action=\" ";
		#src//views/updateform.tt:1: characters 9-16
		++$ret->length;

		#src//views/updateform.tt:1: characters 70-74
		if (!$this->mod) {
			#src//views/updateform.tt:1: characters 70-77
			$ret->arr[$ret->length] = "/filesRec";
			#src//views/updateform.tt:1: characters 70-77
			++$ret->length;
		} else {
			#src//views/updateform.tt:1: characters 92-94
			$ret->arr[$ret->length] = "/filesUpdate";
			#src//views/updateform.tt:1: characters 92-94
			++$ret->length;
		}
		#src//views/updateform.tt:1: characters 108-113
		$ret->arr[$ret->length] = "\" method=\"post\" enctype=\"multipart/form-data\">\x0A        ";
		#src//views/updateform.tt:1: characters 108-113
		++$ret->length;

		#src//views/updateform.tt:1: characters 173-176
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 173-178
			$ret->arr[$ret->length] = "<input type=\"hidden\" name=\"id\" value=\"";
			#src//views/updateform.tt:1: characters 173-178
			++$ret->length;

			#src//views/updateform.tt:1: characters 218-224
			$b1 = Html_Impl_::of($this->rec->id);
			#src//views/updateform.tt:1: characters 218-224
			$ret->arr[$ret->length] = $b1;
			#src//views/updateform.tt:1: characters 218-224
			++$ret->length;

			#src//views/updateform.tt:1: characters 218-226
			$ret->arr[$ret->length] = "\"/>";
			#src//views/updateform.tt:1: characters 218-226
			++$ret->length;

		}
		#src//views/updateform.tt:1: characters 231-248
		$ret->arr[$ret->length] = "<div class=\"field\">\x0A            <label>Sound</label>\x0A            ";
		#src//views/updateform.tt:1: characters 231-248
		++$ret->length;

		#src//views/updateform.tt:1: characters 319-322
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 319-325
			$ret->arr[$ret->length] = "\x0A            <p>";
			#src//views/updateform.tt:1: characters 319-325
			++$ret->length;

			#src//views/updateform.tt:1: characters 343-355
			$b2 = Html_Impl_::escape($this->rec->soundUrl);
			#src//views/updateform.tt:1: characters 343-355
			$ret->arr[$ret->length] = $b2;
			#src//views/updateform.tt:1: characters 343-355
			++$ret->length;

			#src//views/updateform.tt:1: characters 343-357
			$ret->arr[$ret->length] = "</p>\x0A            <audio controls>\x0A        <source src=\"/";
			#src//views/updateform.tt:1: characters 343-357
			++$ret->length;

			#src//views/updateform.tt:1: characters 415-427
			$b3 = Html_Impl_::escape($this->rec->soundUrl);
			#src//views/updateform.tt:1: characters 415-427
			$ret->arr[$ret->length] = $b3;
			#src//views/updateform.tt:1: characters 415-427
			++$ret->length;

			#src//views/updateform.tt:1: characters 415-429
			$ret->arr[$ret->length] = "\" type=\"audio/mpeg\">\x0A      Your browser does not support the audio element.\x0A      </audio>\x0A         ";
			#src//views/updateform.tt:1: characters 415-429
			++$ret->length;

		}
		#src//views/updateform.tt:1: characters 531-549
		$ret->arr[$ret->length] = "<input name=\"fileToUpload\" id=\"file-input\" type=\"file\" value=\"";
		#src//views/updateform.tt:1: characters 531-549
		++$ret->length;

		#src//views/updateform.tt:1: characters 616-619
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 616-622
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 616-622
			++$ret->length;

			#src//views/updateform.tt:1: characters 625-637
			$b4 = Html_Impl_::escape($this->rec->soundUrl);
			#src//views/updateform.tt:1: characters 625-637
			$ret->arr[$ret->length] = $b4;
			#src//views/updateform.tt:1: characters 625-637
			++$ret->length;

			#src//views/updateform.tt:1: characters 625-639
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 625-639
			++$ret->length;

		} else {
			#src//views/updateform.tt:1: characters 646-648
			$ret->arr[$ret->length] = "  ";
			#src//views/updateform.tt:1: characters 646-648
			++$ret->length;
		}
		#src//views/updateform.tt:1: characters 652-658
		$ret->arr[$ret->length] = "\"/>\x0A          </div>\x0A          <div class=\"field\">\x0A            <label>image</label>\x0A                ";
		#src//views/updateform.tt:1: characters 652-658
		++$ret->length;

		#src//views/updateform.tt:1: characters 764-767
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 764-770
			$ret->arr[$ret->length] = "\x0A                <p>";
			#src//views/updateform.tt:1: characters 764-770
			++$ret->length;

			#src//views/updateform.tt:1: characters 792-804
			$b5 = Html_Impl_::escape($this->rec->imageUrl);
			#src//views/updateform.tt:1: characters 792-804
			$ret->arr[$ret->length] = $b5;
			#src//views/updateform.tt:1: characters 792-804
			++$ret->length;

			#src//views/updateform.tt:1: characters 792-806
			$ret->arr[$ret->length] = "</p>\x0A                <img class=\"item-image\" src=\"/";
			#src//views/updateform.tt:1: characters 792-806
			++$ret->length;

			#src//views/updateform.tt:1: characters 859-871
			$b6 = Html_Impl_::escape($this->rec->imageUrl);
			#src//views/updateform.tt:1: characters 859-871
			$ret->arr[$ret->length] = $b6;
			#src//views/updateform.tt:1: characters 859-871
			++$ret->length;

			#src//views/updateform.tt:1: characters 859-873
			$ret->arr[$ret->length] = "\"/>\x0A                ";
			#src//views/updateform.tt:1: characters 859-873
			++$ret->length;

		}
		#src//views/updateform.tt:1: characters 895-913
		$ret->arr[$ret->length] = "<input name=\"imgToUpload\" id=\"image-input\" type=\"file\" value=\"";
		#src//views/updateform.tt:1: characters 895-913
		++$ret->length;

		#src//views/updateform.tt:1: characters 980-983
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 980-986
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 980-986
			++$ret->length;

			#src//views/updateform.tt:1: characters 989-1001
			$b7 = Html_Impl_::escape($this->rec->imageUrl);
			#src//views/updateform.tt:1: characters 989-1001
			$ret->arr[$ret->length] = $b7;
			#src//views/updateform.tt:1: characters 989-1001
			++$ret->length;

			#src//views/updateform.tt:1: characters 989-1003
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 989-1003
			++$ret->length;

		} else {
			#src//views/updateform.tt:1: characters 1010-1012
			$ret->arr[$ret->length] = "  ";
			#src//views/updateform.tt:1: characters 1010-1012
			++$ret->length;
		}
		#src//views/updateform.tt:1: characters 1016-1021
		$ret->arr[$ret->length] = "\"/>\x0A          </div>\x0A          <div class=\"field\">\x0A            <label>titre</label>\x0A            <input type=\"text\" name=\"title\" value=\"";
		#src//views/updateform.tt:1: characters 1016-1021
		++$ret->length;

		#src//views/updateform.tt:1: characters 1161-1164
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 1161-1167
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 1161-1167
			++$ret->length;

			#src//views/updateform.tt:1: characters 1170-1179
			$b8 = Html_Impl_::escape($this->rec->title);
			#src//views/updateform.tt:1: characters 1170-1179
			$ret->arr[$ret->length] = $b8;
			#src//views/updateform.tt:1: characters 1170-1179
			++$ret->length;

			#src//views/updateform.tt:1: characters 1170-1181
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 1170-1181
			++$ret->length;

		} else {
			#src//views/updateform.tt:1: characters 1188-1190
			$ret->arr[$ret->length] = "  ";
			#src//views/updateform.tt:1: characters 1188-1190
			++$ret->length;
		}
		#src//views/updateform.tt:1: characters 1194-1199
		$ret->arr[$ret->length] = "\"/>\x0A          </div>\x0A          <div class=\"field\">\x0A            <label>description</label>\x0A            <textarea type=\"text\" name=\"desc\" >";
		#src//views/updateform.tt:1: characters 1194-1199
		++$ret->length;

		#src//views/updateform.tt:1: characters 1341-1344
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 1341-1347
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 1341-1347
			++$ret->length;

			#src//views/updateform.tt:1: characters 1350-1358
			$b9 = Html_Impl_::escape($this->rec->desc);
			#src//views/updateform.tt:1: characters 1350-1358
			$ret->arr[$ret->length] = $b9;
			#src//views/updateform.tt:1: characters 1350-1358
			++$ret->length;

			#src//views/updateform.tt:1: characters 1350-1360
			$ret->arr[$ret->length] = " ";
			#src//views/updateform.tt:1: characters 1350-1360
			++$ret->length;

		} else {
			#src//views/updateform.tt:1: characters 1367-1369
			$ret->arr[$ret->length] = "  ";
			#src//views/updateform.tt:1: characters 1367-1369
			++$ret->length;
		}
		#src//views/updateform.tt:1: characters 1373-1378
		$ret->arr[$ret->length] = "</textarea>\x0A          </div>\x0A        <button class=\"ui button\" type=\"submit\">Submit</button>\x0A        <div class=\"ui error message\">\x0A        </div>\x0A      </form>\x0A      ";
		#src//views/updateform.tt:1: characters 1373-1378
		++$ret->length;

		#src//views/updateform.tt:1: characters 1550-1553
		if ($this->mod) {
			#src//views/updateform.tt:1: characters 1550-1556
			$ret->arr[$ret->length] = "\x0A      <a href=\"/delete/";
			#src//views/updateform.tt:1: characters 1550-1556
			++$ret->length;

			#src//views/updateform.tt:1: characters 1582-1588
			$b10 = Html_Impl_::of($this->rec->id);
			#src//views/updateform.tt:1: characters 1582-1588
			$ret->arr[$ret->length] = $b10;
			#src//views/updateform.tt:1: characters 1582-1588
			++$ret->length;

			#src//views/updateform.tt:1: characters 1582-1590
			$ret->arr[$ret->length] = "\" class=\"ui button\" >suppr</a>\x0A      ";
			#src//views/updateform.tt:1: characters 1582-1590
			++$ret->length;

		}

		#/Users/ut/haxe/haxe_libraries/tink_template/0.3.3/github/947e330e7f57a4877b12c253baac6311cfb5530b/src/tink/template/Generator.hx:121: characters 19-30
		return HtmlBuffer_Impl_::collapse($ret);
	}
}


Boot::registerClass(UpView::class, 'views.UpView');
