<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Closures implementation
 */
class HxClosure {
	/**
	 * @var string
	 * Method name for methods
	 */
	public $func;
	/**
	 * @var mixed
	 * `this` for instance methods; php class name for static methods
	 */
	public $target;


	/**
	 * @param mixed $target
	 * @param string $func
	 * 
	 * @return void
	 */
	public function __construct ($target, $func) {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:834: characters 3-23
		$this->target = $target;
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:835: characters 3-19
		$this->func = $func;
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:837: lines 837-839
		if (is_null($target)) {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:838: characters 4-9
			throw new HxException("Unable to create closure on `null`");
		}
	}


	/**
	 * @see http://php.net/manual/en/language.oop5.magic.php#object.invoke
	 * 
	 * @return mixed
	 */
	public function __invoke () {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:847: characters 3-76
		return call_user_func_array($this->getCallback(), func_get_args());
	}


	/**
	 * Invoke this closure with `newThis` instead of `this`
	 * 
	 * @param mixed $newThis
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function callWith ($newThis, $args) {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:876: characters 3-65
		return call_user_func_array($this->getCallback($newThis), $args);
	}


	/**
	 * Check if this is the same closure
	 * 
	 * @param HxClosure $closure
	 * 
	 * @return bool
	 */
	public function equals ($closure) {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:869: characters 10-60
		if (Boot::equal($this->target, $closure->target)) {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:869: characters 39-59
			return $this->func === $closure->func;
		} else {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:869: characters 10-60
			return false;
		}
	}


	/**
	 * Generates callable value for PHP
	 * 
	 * @param mixed $eThis
	 * 
	 * @return mixed
	 */
	public function getCallback ($eThis = null) {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:854: lines 854-856
		if ($eThis === null) {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:855: characters 4-18
			$eThis = $this->target;
		}
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:857: lines 857-861
		if (($eThis instanceof \StdClass)) {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:858: lines 858-860
			if (($eThis instanceof HxAnon)) {
				#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:859: characters 25-30
				$tmp = $eThis;
				#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:859: characters 32-36
				$tmp1 = $this->func;
				#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:859: characters 5-37
				return $tmp->{$tmp1};
			}
		}
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:862: characters 3-39
		return [$eThis, $this->func];
	}
}


Boot::registerClass(HxClosure::class, 'php._Boot.HxClosure');
