<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Base class for enum types
 */
class HxEnum {
	/**
	 * @var int
	 */
	public $index;
	/**
	 * @var mixed
	 */
	public $params;
	/**
	 * @var string
	 */
	public $tag;


	/**
	 * @param string $tag
	 * @param int $index
	 * @param mixed $arguments
	 * 
	 * @return void
	 */
	public function __construct ($tag, $index, $arguments = null) {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:594: characters 3-17
		$this->tag = $tag;
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:595: characters 3-21
		$this->index = $index;
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:596: characters 3-63
		$this->params = ($arguments === null ? [] : $arguments);
	}


	/**
	 * PHP magic method to get string representation of this `Class`
	 * 
	 * @return string
	 */
	public function __toString () {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:611: characters 3-20
		$result = $this->tag;
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:612: lines 612-615
		if (count($this->params) > 0) {
			#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:614: characters 4-54
			$result = ($result??'null') . (("(" . (implode(",", array_map(function ($item) {
				#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:613: characters 51-78
				return Boot::stringify($item);
			}, $this->params))??'null') . ")")??'null');
		}
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:616: characters 3-16
		return $result;
	}


	/**
	 * Get string representation of this `Class`
	 * 
	 * @return string
	 */
	public function toString () {
		#/Users/ut/haxe/versions/4.0.0-preview.3/std/php/Boot.hx:603: characters 3-22
		return $this->__toString();
	}
}


Boot::registerClass(HxEnum::class, 'php._Boot.HxEnum');
