<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\json;

use \tink\core\Outcome;
use \php\Boot;
use \php\_Boot\HxException;
use \tink\core\TypedError;
use \tink\web\forms\_FormFile\FormFile_Impl_;
use \php\_Boot\HxString;
use \haxe\io\Bytes;
use \haxe\io\_BytesData\Container;
use \tink\json\_Parser\JsonString_Impl_;
use \php\_Boot\HxAnon;

class Parser0 extends BasicParser {
	/**
	 * @return void
	 */
	public function __construct () {
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/Macro.hx:75: characters 29-36
		parent::__construct();
	}


	/**
	 * @param string $source
	 * 
	 * @return object
	 */
	public function parse ($source) {
		#src/Server.hx:114: lines 114-149
		$this->init($source);
		#src/Server.hx:114: lines 114-149
		return $this->parse0();
	}


	/**
	 * @return object
	 */
	public function parse0 () {
		#src/Server.hx:114: lines 114-149
		$_gthis = $this;
		#src/Server.hx:114: lines 114-149
		$v_desc = null;
		#src/Server.hx:114: lines 114-149
		$hasv_desc = false;
		#src/Server.hx:114: lines 114-149
		$v_fileToUpload = null;
		#src/Server.hx:114: lines 114-149
		$hasv_fileToUpload = false;
		#src/Server.hx:114: lines 114-149
		$v_imgToUpload = null;
		#src/Server.hx:114: lines 114-149
		$hasv_imgToUpload = false;
		#src/Server.hx:114: lines 114-149
		$v_title = null;
		#src/Server.hx:114: lines 114-149
		$hasv_title = false;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:175: characters 7-32
		$__start__ = $this->pos;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
		while (true) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$tmp = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if ($this->pos < $this->max) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$s = $this->source;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$index = $this->pos;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp = ((strlen($s) === $index ? 0 : ord($s[$index]))) < 33;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if (!$tmp) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				break;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$this->pos++;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
		$tmp1 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		$tmp2 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		if ($this->max > $this->pos) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$s1 = $this->source;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$index1 = $this->pos;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp2 = ((strlen($s1) === $index1 ? 0 : ord($s1[$index1]))) === 123;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp2 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
		if ($tmp2) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:176: characters 7-11
			$tmp3 = $this;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
			$tmp3->pos = $tmp3->pos + 1;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$tmp4 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if ($this->pos < $this->max) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$s2 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$index2 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp4 = ((strlen($s2) === $index2 ? 0 : ord($s2[$index2]))) < 33;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp4 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if (!$tmp4) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					break;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$this->pos++;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp1 = true;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp1 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 18-154
		if (!$tmp1) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 76-108
			$this->die("Expected {");
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
		while (true) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$tmp5 = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if ($this->pos < $this->max) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$s3 = $this->source;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$index3 = $this->pos;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp5 = ((strlen($s3) === $index3 ? 0 : ord($s3[$index3]))) < 33;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp5 = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if (!$tmp5) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				break;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$this->pos++;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
		$tmp6 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		$tmp7 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		if ($this->max > $this->pos) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$s4 = $this->source;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$index4 = $this->pos;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp7 = ((strlen($s4) === $index4 ? 0 : ord($s4[$index4]))) === 125;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp7 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
		if ($tmp7) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:177: characters 12-16
			$tmp8 = $this;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
			$tmp8->pos = $tmp8->pos + 1;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$tmp9 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if ($this->pos < $this->max) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$s5 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$index5 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp9 = ((strlen($s5) === $index5 ? 0 : ord($s5[$index5]))) < 33;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp9 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if (!$tmp9) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					break;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$this->pos++;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp6 = true;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp6 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:177: lines 177-184
		if (!$tmp6) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:178: lines 178-182
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:179: characters 11-45
				$__name__ = $this->parseString();
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				while (true) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp10 = null;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if ($this->pos < $this->max) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$s6 = $this->source;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$index6 = $this->pos;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp10 = ((strlen($s6) === $index6 ? 0 : ord($s6[$index6]))) < 33;
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp10 = false;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if (!$tmp10) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						break;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$this->pos++;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp11 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp12 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				if ($this->max > $this->pos) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$s7 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$index7 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp12 = ((strlen($s7) === $index7 ? 0 : ord($s7[$index7]))) === 58;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp12 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
				if ($tmp12) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:180: characters 11-15
					$tmp13 = $this;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
					$tmp13->pos = $tmp13->pos + 1;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					while (true) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp14 = null;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if ($this->pos < $this->max) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$s8 = $this->source;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$index8 = $this->pos;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp14 = ((strlen($s8) === $index8 ? 0 : ord($s8[$index8]))) < 33;
						} else {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp14 = false;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if (!$tmp14) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							break;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$this->pos++;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp11 = true;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp11 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 18-154
				if (!$tmp11) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 76-108
					$this->die("Expected :");
				}
				#src/Server.hx:118: characters 3-15
				if ((strlen("title") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "title")) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:100: characters 25-43
					$v_title = JsonString_Impl_::toString($this->parseString());
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_title = true;
				} else if ((strlen("imgToUpload") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "imgToUpload")) {
					#src/Server.hx:116: characters 3-23
					$__start__1 = $this->pos;
					#src/Server.hx:116: characters 3-23
					$rep = $this->parse1();
					#src/Server.hx:116: characters 3-23
					try {
						#src/Server.hx:116: characters 3-23
						$v_imgToUpload = FormFile_Impl_::ofJson($rep);
					} catch (\Throwable $__hx__caught_e) {
						$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
						$e = $__hx__real_e;
						#src/Server.hx:116: characters 3-23
						$v_imgToUpload = $this->die(\Std::string($e), $__start__1);
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_imgToUpload = true;
				} else if ((strlen("fileToUpload") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "fileToUpload")) {
					#src/Server.hx:115: characters 3-24
					$__start__2 = $this->pos;
					#src/Server.hx:115: characters 3-24
					$rep1 = $this->parse1();
					#src/Server.hx:115: characters 3-24
					try {
						#src/Server.hx:115: characters 3-24
						$v_fileToUpload = FormFile_Impl_::ofJson($rep1);
					} catch (\Throwable $__hx__caught_e) {
						$__hx__real_e = ($__hx__caught_e instanceof HxException ? $__hx__caught_e->e : $__hx__caught_e);
						$e1 = $__hx__real_e;
						#src/Server.hx:115: characters 3-24
						$v_fileToUpload = $this->die(\Std::string($e1), $__start__2);
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_fileToUpload = true;
				} else if ((strlen("desc") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "desc")) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:100: characters 25-43
					$v_desc = JsonString_Impl_::toString($this->parseString());
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_desc = true;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:67: characters 22-38
					$this->skipValue();
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				while (true) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp15 = null;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if ($this->pos < $this->max) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$s9 = $this->source;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$index9 = $this->pos;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp15 = ((strlen($s9) === $index9 ? 0 : ord($s9[$index9]))) < 33;
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp15 = false;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if (!$tmp15) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						break;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$this->pos++;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp16 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp17 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				if ($this->max > $this->pos) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$s10 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$index10 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp17 = ((strlen($s10) === $index10 ? 0 : ord($s10[$index10]))) === 44;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp17 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
				if ($tmp17) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:182: characters 18-22
					$tmp18 = $this;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
					$tmp18->pos = $tmp18->pos + 1;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					while (true) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp19 = null;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if ($this->pos < $this->max) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$s11 = $this->source;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$index11 = $this->pos;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp19 = ((strlen($s11) === $index11 ? 0 : ord($s11[$index11]))) < 33;
						} else {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp19 = false;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if (!$tmp19) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							break;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$this->pos++;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp16 = true;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp16 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:178: lines 178-182
				if (!$tmp16) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:178: lines 178-182
					break;
				}
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp20 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				if ($this->pos < $this->max) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$s12 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$index12 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp20 = ((strlen($s12) === $index12 ? 0 : ord($s12[$index12]))) < 33;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp20 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				if (!$tmp20) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					break;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$this->pos++;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp21 = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp22 = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			if ($this->max > $this->pos) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
				$s13 = $this->source;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
				$index13 = $this->pos;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp22 = ((strlen($s13) === $index13 ? 0 : ord($s13[$index13]))) === 125;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp22 = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
			if ($tmp22) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:183: characters 9-13
				$tmp23 = $this;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
				$tmp23->pos = $tmp23->pos + 1;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				while (true) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp24 = null;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					if ($this->pos < $this->max) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$s14 = $this->source;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$index14 = $this->pos;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp24 = ((strlen($s14) === $index14 ? 0 : ord($s14[$index14]))) < 33;
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp24 = false;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					if (!$tmp24) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						break;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$this->pos++;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp21 = true;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp21 = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 18-154
			if (!$tmp21) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 76-108
				$this->die("Expected }");
			}
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:186: lines 186-188
		$__missing__ = function ($field)  use (&$__start__, &$_gthis) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:187: characters 9-68
			return $_gthis->die("missing field \"" . ($field??'null') . "\"", $__start__);
		};
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:123: characters 26-82
		$tmp25 = ($hasv_desc ? $v_desc : $__missing__("desc"));
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:123: characters 26-82
		$tmp26 = ($hasv_fileToUpload ? $v_fileToUpload : $__missing__("fileToUpload"));
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:123: characters 26-82
		$tmp27 = ($hasv_imgToUpload ? $v_imgToUpload : $__missing__("imgToUpload"));
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:190: characters 7-39
		return new HxAnon([
			"desc" => $tmp25,
			"fileToUpload" => $tmp26,
			"imgToUpload" => $tmp27,
			"title" => ($hasv_title ? $v_title : $__missing__("title")),
		]);
	}


	/**
	 * @return object
	 */
	public function parse1 () {
		#src/Server.hx:115: characters 3-24
		$_gthis = $this;
		#src/Server.hx:114: lines 114-149
		$v_content = null;
		#src/Server.hx:114: lines 114-149
		$hasv_content = false;
		#src/Server.hx:114: lines 114-149
		$v_fileName = null;
		#src/Server.hx:114: lines 114-149
		$hasv_fileName = false;
		#src/Server.hx:114: lines 114-149
		$v_mimeType = null;
		#src/Server.hx:114: lines 114-149
		$hasv_mimeType = false;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:175: characters 7-32
		$__start__ = $this->pos;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
		while (true) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$tmp = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if ($this->pos < $this->max) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$s = $this->source;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$index = $this->pos;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp = ((strlen($s) === $index ? 0 : ord($s[$index]))) < 33;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if (!$tmp) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				break;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$this->pos++;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
		$tmp1 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		$tmp2 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		if ($this->max > $this->pos) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$s1 = $this->source;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$index1 = $this->pos;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp2 = ((strlen($s1) === $index1 ? 0 : ord($s1[$index1]))) === 123;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp2 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
		if ($tmp2) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:176: characters 7-11
			$tmp3 = $this;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
			$tmp3->pos = $tmp3->pos + 1;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$tmp4 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if ($this->pos < $this->max) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$s2 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$index2 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp4 = ((strlen($s2) === $index2 ? 0 : ord($s2[$index2]))) < 33;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp4 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if (!$tmp4) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					break;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$this->pos++;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp1 = true;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp1 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 18-154
		if (!$tmp1) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 76-108
			$this->die("Expected {");
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
		while (true) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$tmp5 = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if ($this->pos < $this->max) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$s3 = $this->source;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$index3 = $this->pos;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp5 = ((strlen($s3) === $index3 ? 0 : ord($s3[$index3]))) < 33;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp5 = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			if (!$tmp5) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				break;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			$this->pos++;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
		$tmp6 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		$tmp7 = null;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
		if ($this->max > $this->pos) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$s4 = $this->source;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
			$index4 = $this->pos;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp7 = ((strlen($s4) === $index4 ? 0 : ord($s4[$index4]))) === 125;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp7 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
		if ($tmp7) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:177: characters 12-16
			$tmp8 = $this;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
			$tmp8->pos = $tmp8->pos + 1;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$tmp9 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if ($this->pos < $this->max) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$s5 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$index5 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp9 = ((strlen($s5) === $index5 ? 0 : ord($s5[$index5]))) < 33;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp9 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				if (!$tmp9) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					break;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				$this->pos++;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp6 = true;
		} else {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp6 = false;
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:177: lines 177-184
		if (!$tmp6) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:178: lines 178-182
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:179: characters 11-45
				$__name__ = $this->parseString();
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				while (true) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp10 = null;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if ($this->pos < $this->max) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$s6 = $this->source;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$index6 = $this->pos;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp10 = ((strlen($s6) === $index6 ? 0 : ord($s6[$index6]))) < 33;
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp10 = false;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if (!$tmp10) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						break;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$this->pos++;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp11 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp12 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				if ($this->max > $this->pos) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$s7 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$index7 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp12 = ((strlen($s7) === $index7 ? 0 : ord($s7[$index7]))) === 58;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp12 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
				if ($tmp12) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:180: characters 11-15
					$tmp13 = $this;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
					$tmp13->pos = $tmp13->pos + 1;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					while (true) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp14 = null;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if ($this->pos < $this->max) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$s8 = $this->source;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$index8 = $this->pos;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp14 = ((strlen($s8) === $index8 ? 0 : ord($s8[$index8]))) < 33;
						} else {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp14 = false;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if (!$tmp14) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							break;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$this->pos++;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp11 = true;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp11 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 18-154
				if (!$tmp11) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 76-108
					$this->die("Expected :");
				}
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/forms/FormFile.hx:12: characters 3-18
				if ((strlen("mimeType") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "mimeType")) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:100: characters 25-43
					$v_mimeType = JsonString_Impl_::toString($this->parseString());
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_mimeType = true;
				} else if ((strlen("fileName") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "fileName")) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:100: characters 25-43
					$v_fileName = JsonString_Impl_::toString($this->parseString());
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_fileName = true;
				} else if ((strlen("content") === ($__name__->max - $__name__->min)) && (HxString::substring($__name__->source, $__name__->min, $__name__->max) === "content")) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:48: characters 18-74
					$s9 = base64_decode(JsonString_Impl_::toString($this->parseString()), true);
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:48: characters 18-74
					$v_content = new Bytes(strlen($s9), new Container($s9));
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:105: characters 26-42
					$hasv_content = true;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:67: characters 22-38
					$this->skipValue();
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				while (true) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp15 = null;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if ($this->pos < $this->max) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$s10 = $this->source;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$index9 = $this->pos;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp15 = ((strlen($s10) === $index9 ? 0 : ord($s10[$index9]))) < 33;
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						$tmp15 = false;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					if (!$tmp15) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
						break;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$this->pos++;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp16 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp17 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				if ($this->max > $this->pos) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$s11 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
					$index10 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp17 = ((strlen($s11) === $index10 ? 0 : ord($s11[$index10]))) === 44;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
					$tmp17 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
				if ($tmp17) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:182: characters 18-22
					$tmp18 = $this;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
					$tmp18->pos = $tmp18->pos + 1;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					while (true) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp19 = null;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if ($this->pos < $this->max) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$s12 = $this->source;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$index11 = $this->pos;
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp19 = ((strlen($s12) === $index11 ? 0 : ord($s12[$index11]))) < 33;
						} else {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							$tmp19 = false;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						if (!$tmp19) {
							#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
							break;
						}
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$this->pos++;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp16 = true;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
					$tmp16 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:178: lines 178-182
				if (!$tmp16) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:178: lines 178-182
					break;
				}
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
			while (true) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$tmp20 = null;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				if ($this->pos < $this->max) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$s13 = $this->source;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$index12 = $this->pos;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp20 = ((strlen($s13) === $index12 ? 0 : ord($s13[$index12]))) < 33;
				} else {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					$tmp20 = false;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				if (!$tmp20) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
					break;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:382: characters 9-29
				$this->pos++;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
			$tmp21 = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			$tmp22 = null;
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
			if ($this->max > $this->pos) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
				$s14 = $this->source;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 27-84
				$index13 = $this->pos;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp22 = ((strlen($s14) === $index13 ? 0 : ord($s14[$index13]))) === 125;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:378: characters 19-107
				$tmp22 = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:383: lines 383-389
			if ($tmp22) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:183: characters 9-13
				$tmp23 = $this;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:384: characters 9-35
				$tmp23->pos = $tmp23->pos + 1;
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
				while (true) {
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$tmp24 = null;
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					if ($this->pos < $this->max) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$s15 = $this->source;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$index14 = $this->pos;
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp24 = ((strlen($s15) === $index14 ? 0 : ord($s15[$index14]))) < 33;
					} else {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						$tmp24 = false;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					if (!$tmp24) {
						#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
						break;
					}
					#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:386: characters 11-31
					$this->pos++;
				}
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp21 = true;
			} else {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:380: lines 380-390
				$tmp21 = false;
			}
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 18-154
			if (!$tmp21) {
				#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/Parser.hx:367: characters 76-108
				$this->die("Expected }");
			}
		}
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:186: lines 186-188
		$__missing__ = function ($field)  use (&$__start__, &$_gthis) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:187: characters 9-68
			return $_gthis->die("missing field \"" . ($field??'null') . "\"", $__start__);
		};
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:123: characters 26-82
		$tmp25 = ($hasv_content ? $v_content : $__missing__("content"));
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:123: characters 26-82
		$tmp26 = ($hasv_fileName ? $v_fileName : $__missing__("fileName"));
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/GenReader.hx:190: characters 7-39
		return new HxAnon([
			"content" => $tmp25,
			"fileName" => $tmp26,
			"mimeType" => ($hasv_mimeType ? $v_mimeType : $__missing__("mimeType")),
		]);
	}


	/**
	 * @param string $source
	 * 
	 * @return Outcome
	 */
	public function tryParse ($source) {
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/Macro.hx:90: lines 90-91
		$_gthis = $this;
		#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/Macro.hx:91: characters 9-81
		return TypedError::catchExceptions(function ()  use (&$source, &$_gthis) {
			#/Users/ut/haxe/haxe_libraries/tink_json/0.9.0/haxelib/src/tink/json/macros/Macro.hx:91: characters 60-80
			return $_gthis->parse($source);
		}, null, new HxAnon([
			"fileName" => "tink/json/macros/Macro.hx",
			"lineNumber" => 91,
			"className" => "tink.json.Parser0",
			"methodName" => "tryParse",
		]));
	}
}


Boot::registerClass(Parser0::class, 'tink.json.Parser0');
