<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\core\_Callback;

use \php\Boot;

interface LinkObject {
	/**
	 * @return void
	 */
	public function cancel () ;
}


Boot::registerClass(LinkObject::class, 'tink.core._Callback.LinkObject');
