<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\http;

use \php\Boot;
use \tink\streams\StreamObject;

class Chunked {
	/**
	 * @var ChunkedDecoder
	 */
	static public $_decoder;
	/**
	 * @var ChunkedEncoder
	 */
	static public $_encoder;


	/**
	 * @param StreamObject $source
	 * 
	 * @return StreamObject
	 */
	static public function decode ($source) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:31: characters 3-37
		return Chunked::decoder()->transform($source);
	}


	/**
	 * @return ChunkedDecoder
	 */
	static public function decoder () {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:23: characters 3-55
		if (Chunked::$_decoder === null) {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:23: characters 24-55
			Chunked::$_decoder = new ChunkedDecoder();
		}
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:24: characters 3-23
		return Chunked::$_decoder;
	}


	/**
	 * @param StreamObject $source
	 * 
	 * @return StreamObject
	 */
	static public function encode ($source) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:28: characters 3-37
		return Chunked::encoder()->transform($source);
	}


	/**
	 * @return ChunkedEncoder
	 */
	static public function encoder () {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:18: characters 3-55
		if (Chunked::$_encoder === null) {
			#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:18: characters 24-55
			Chunked::$_encoder = new ChunkedEncoder();
		}
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Chunked.hx:19: characters 3-23
		return Chunked::$_encoder;
	}
}


Boot::registerClass(Chunked::class, 'tink.http.Chunked');
