<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\http;

use \php\Boot;

interface MiddlewareObject {
	/**
	 * @param HandlerObject $handler
	 * 
	 * @return HandlerObject
	 */
	public function apply ($handler) ;
}


Boot::registerClass(MiddlewareObject::class, 'tink.http.MiddlewareObject');
