<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\http;

use \php\Boot;
use \tink\core\_Future\FutureObject;

class SimpleHandler implements HandlerObject {
	/**
	 * @var \Closure
	 */
	public $f;


	/**
	 * @param \Closure $f
	 * 
	 * @return void
	 */
	public function __construct ($f) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Handler.hx:27: characters 5-15
		$this->f = $f;
	}


	/**
	 * @param IncomingRequest $req
	 * 
	 * @return FutureObject
	 */
	public function process ($req) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Handler.hx:30: characters 5-18
		return ($this->f)($req);
	}
}


Boot::registerClass(SimpleHandler::class, 'tink.http.SimpleHandler');
