<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\web\routing\_Context;

use \tink\core\_Promise\Promise_Impl_;
use \tink\core\Outcome;
use \php\Boot;
use \tink\core\_Future\SyncFuture;
use \tink\core\_Lazy\LazyConst;

final class RequestReader_Impl_ {
	/**
	 * @param \Closure $read
	 * 
	 * @return \Closure
	 */
	static public function ofSafeStringReader ($read) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/routing/Context.hx:203: characters 5-64
		return RequestReader_Impl_::ofStringReader(function ($s)  use (&$read) {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/routing/Context.hx:203: characters 40-63
			return Outcome::Success($read($s));
		});
	}


	/**
	 * @param \Closure $read
	 * 
	 * @return \Closure
	 */
	static public function ofStringReader ($read) {
		#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/routing/Context.hx:197: lines 197-200
		return function ($ctx)  use (&$read) {
			#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/routing/Context.hx:199: lines 199-200
			return Promise_Impl_::next($ctx->allRaw(), function ($body)  use (&$read) {
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/routing/Context.hx:200: characters 57-72
				$o = $body->toString();
				#/Users/ut/haxe/haxe_libraries/tink_web/0.1.4/github/7c93ab66f476c97e62510c653bb4e58e918e1471/src/tink/web/routing/Context.hx:200: characters 45-73
				return new SyncFuture(new LazyConst($read($o)));
			});
		};
	}
}


Boot::registerClass(RequestReader_Impl_::class, 'tink.web.routing._Context.RequestReader_Impl_');
