<?php
/**
 * Generated by Haxe 4.0.0 (git build development @ 3018ab1)
 */

namespace tink\http\_Method;

use \php\Boot;

final class Method_Impl_ {


	/**
	 * @param string $s
	 * @param \Closure $fallback
	 * 
	 * @return string
	 */
	static public function ofString ($s, $fallback) {
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:14: characters 19-34
		$_g = strtoupper($s);
		#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:14: characters 19-34
		switch ($_g) {
			case "DELETE":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:21: characters 22-28
				return "DELETE";
				break;
			case "GET":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:15: characters 19-22
				return "GET";
				break;
			case "HEAD":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:16: characters 20-24
				return "HEAD";
				break;
			case "OPTIONS":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:17: characters 23-30
				return "OPTIONS";
				break;
			case "PATCH":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:20: characters 21-26
				return "PATCH";
				break;
			case "POST":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:18: characters 20-24
				return "POST";
				break;
			case "PUT":
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:19: characters 19-22
				return "PUT";
				break;
			default:
				#/Users/ut/haxe/haxe_libraries/tink_http/0.8.2/github/403eb075dff5d7b8ec4a9e08052eb01e1e196722/src/tink/http/Method.hx:22: characters 15-26
				return $fallback($_g);
				break;
		}
	}
}


Boot::registerClass(Method_Impl_::class, 'tink.http._Method.Method_Impl_');
